import = [
   "~/.config/alacritty/themes/catppuccin_mocha.toml",
]

[cursor.style]
blinking = "Always"

[window]
opacity = 1
blur = true
startup_mode = "Fullscreen"
padding = { x = 10, y = 10 }

[font]
size = 16
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
