
[cursor.style]
blinking = 'Always'

[window]
opacity = 0.9
blur = true
startup_mode = 'Fullscreen'
padding = { x = 10, y = 10 }
decorations_theme_variant = 'Dark'

[font]
size = 16
normal = { family = 'ComicShannsMono Nerd Font', style = 'Regular' }
bold = { style = 'Regular' }
offset = { x = 1 }

[general]
import = [
	'/Users/kirankoirala/.config/alacritty/themes/catppuccin.toml',
]
