
[cursor.style]
blinking = 'Always'

[window]
opacity = 0.8
blur = true
position = { x = 100, y = 100 }
# startup_mode = 'SimpleFullscreen'
#decorations = "None"
padding = { x = 10, y = 10 }
dimensions = { columns = 190, lines = 45 }
decorations_theme_variant = 'Dark'

[font]
size = 13
normal = { family = 'ComicShannsMono Nerd Font', style = 'Regular' }
bold = { style = 'Regular' }
offset = { x = 1 }

[general]
import = [
	'/Users/kirankoirala/.config/alacritty/themes/catppuccin.toml',
]
